const st=m=>{const e=$('#st');e.textContent=m;e.style.display='block';clearTimeout(st.t);st.t=setTimeout(()=>e.style.display='none',4500)};
const showX=m=>{$('#xpt').textContent=m||'';$('#xp').classList.toggle('open',m!=null)};
const ic=(n,t,id,c)=>`<button class="${c||'secondary'} interactive" id="${id}" data-tip="${t}" aria-label="${t}"><img class="icon" src="${UI}${n}.png" alt=""></button>`;
$('#fb').innerHTML=ic('menu','Menu','tp')+ic('move','Move','fm2')+ic('rotate','Rotate','fr2','primary')+ic('eye_open','Reset camera','fc')+ic('chevron_up','Higher parent','fp')+ic('home','Select root','fg')+ic('hand','Camera move','fh')+ic('undo','Undo','fd0')+ic('redo','Redo','fd')+ic('mirror','Mirror','fx')+ic('refresh','Reset','fz')+ic('lock','Lock player','fl')+`<button class="theme-toggle interactive" onclick="toggleTheme()" aria-label="Toggle theme"><img id="theme-icon" class="icon" src="${UI}moon.png" alt=""></button>`;
const fillR=r=>r.style.setProperty('--p',((r.value-r.min)/(r.max-r.min)*100)+'%');
const dk=(k,r)=>`data-k="${k}"${r?' data-r="1"':''}`;
const sl=(k,t,a,b,s,r)=>`<label class="row sl"><span>${t}</span><input type="range" min="${a}" max="${b}" step="${s}" ${dk(k,r)} value="${P[k]}"><input type="number" class="nv" inputmode="decimal" step="any" ${dk(k,r)} value="${P[k]}"></label>`;
const ck=(k,t,r)=>`<label class="row"><input type="checkbox" ${dk(k,r)} ${P[k]?'checked':''}><span class="grow">${t}</span></label>`;
const col=(k,t)=>`<label class="row"><span>${t}</span><input type="color" ${dk(k)} value="${P[k]}"></label>`;
const tex=(k,ph)=>`<label class="row"><input type="text" data-s="${k}" placeholder="${ph}"><input type="file" accept="image/*" data-sf="${k}" style="width:76px"></label>`;
const sec=(t,b,o)=>`<details ${o?'open':''}><summary>${t}</summary>${b}</details>`;
$('#p').innerHTML='<div id="gh"><i></i></div><div id="pc"></div>';$('#pc').innerHTML=`<b>Minecraft Poser</b>
${sec('Pose',`<label class="row"><span>Bone</span><select id="bs"></select></label>
<div class="btns"><button id="mr" class="primary interactive">Rotate</button><button id="mt" class="secondary interactive">Move</button><button id="mm" class="secondary interactive">Move whole player</button><button id="rb" class="secondary interactive">Reset bone</button><button id="ra" class="secondary interactive">Reset pose</button><button id="ps" class="secondary interactive">Save pose</button><button id="pl2" class="secondary interactive">Load pose</button><input type="file" id="pf" accept=".json" hidden></div>
<label class="row"><span>Bending</span><select ${dk('bm',1)}><option value="0">Off</option><option value="1">Smooth</option><option value="2">Rigid (hinge)</option></select></label>${sl('bz','Smooth softness',.5,6,.5,1)}${ck('mir','Mirror left and right limbs')}${ck('snap','Snap rotation to 15 degrees')}${ck('wsp','World-space gizmo')}`,1)}
${sec('Players',sl('dep','3D layer thickness',.05,1,.05,1)+ck('a3d','3D armor (extruded inward)',1)+sl('athk','Armor thickness',.1,1,.05,1)+ck('e3d','3D elytra (extruded inward)',1)+sl('ethk','Elytra thickness',.1,1,.05,1)+'<div class="btns"><button class="secondary interactive" data-act="add">+ Add player</button><button class="secondary interactive" data-act="addc">+ Add (copy pose)</button></div><div id="acl"></div>')}
${sec('Light and shadow',ck('shade','Lighting and shadows')+sl('az','Light angle',-180,180,1)+sl('el','Light height',5,90,1)+sl('key','Light intensity',0,4,.05)+col('kc','Light color')+sl('amb','Ambient',0,2,.05)+sl('fill','Fill light',0,2,.05)+col('skc','Fill color')+ck('self','Self shadows')+ck('gs','Ground shadow')+sl('gop','Shadow opacity',0,1,.05)+sl('expo','Exposure',.3,2.5,.05)+ck('bloom','Bloom')+sl('bs','Bloom strength',0,3,.05)+sl('br','Bloom radius',0,1,.05)+sl('bt','Bloom threshold',0,1,.01)+sl('bsw','Bloom softness',0,1,.01)+sl('bfo','Bloom spread (falloff)',.3,1,.01)+sl('bmx','Highlight clamp',1,30,.5))}
${sec('View',sl('fov','FOV',5,160,1)+ck('grid','Grid')+`<label class="row"><span>Preview quality</span><select ${dk('pq')}>${[.35,.5,.75,1,1.5].map(v=>`<option value="${v}" ${P.pq==v?'selected':''}>${Math.round(v*100)}%</option>`).join('')}</select></label><div class="btns">${['front','back','left','right','top'].map(v=>`<button class="secondary interactive" data-v="${v}">${v}</button>`).join('')}</div>`)}
${sec('Render PNG',`<label class="row"><span>Long side</span><select id="es">${[720,1080,1440,2000,2500,3000,4000].map(v=>`<option ${v==1440?'selected':''}>${v}</option>`).join('')}</select></label><label class="row"><span>Quality</span><select id="xq"><option value="0">Normal</option><option value="1" selected>High (2x supersample)</option><option value="2">Ultra (3x supersample)</option></select></label><label class="row"><span>Background</span><select id="xbgm"><option value="0">Transparent</option><option value="1">Solid color</option></select></label><label class="row"><span>BG color</span><input type="color" id="xbgc" value="#ffffff"></label>${ck('crop','Auto-crop to content')}<div class="btns"><button id="ed" class="primary interactive">Download PNG</button><button id="ec" class="secondary interactive">Copy to clipboard</button></div>`)}
${sec('Share scene','<div class="btns"><button id="scc" class="primary interactive">Copy scene code</button><button id="scl" class="secondary interactive">Load from box</button><button id="scd" class="secondary interactive">Download file</button><button id="scu" class="secondary interactive">Load file</button><input type="file" id="scf" accept=".json,.txt" hidden></div><textarea id="sct" rows="4" style="width:100%;box-sizing:border-box;resize:vertical" placeholder="Paste a scene code here, then press Load from box."></textarea><small>Poses, players, lighting and camera are saved. Uploaded image files cannot be stored, so use paths or URLs for textures you want restored.</small>')}
<p class="note">I will add compatibility with shield, cape, and a new prop system (adding blocks, items, beds, and such to the ground), and will improve all the other features.</p>
<div class="footer-editorial">
<p class="footer-editorial-cta">Pose it. Render it.</p>
<div class="footer-editorial-socials">
<a href="https://github.com/nako-hikari/" target="_blank" class="social" aria-label="GitHub"><img src="https://raw.githubusercontent.com/nako-hikari/assets/main/ui/github.png" alt="GitHub"></a>
<a href="https://m.youtube.com/@NaCryst" target="_blank" class="social" aria-label="YouTube"><img src="https://raw.githubusercontent.com/nako-hikari/assets/main/ui/youtube.png" alt="YouTube"></a>
<a href="https://www.tiktok.com/@nako_hikari_mc" target="_blank" class="social" aria-label="TikTok"><img src="https://raw.githubusercontent.com/nako-hikari/assets/main/ui/tiktok.png" alt="TikTok"></a>
<a href="https://ko-fi.com/arialicee" target="_blank" class="social kofi" aria-label="Support on Ko-fi"><img src="https://raw.githubusercontent.com/nako-hikari/assets/main/ui/kofi.png" alt="Ko-fi"></a>
</div>
<p class="footer-editorial-fine">Nako Hikari</p>
</div>`;
document.querySelectorAll('#pc input[type=range]').forEach(fillR);

